### ISSUE TITLE
同步延迟不会被放大吗？

### ISSUE THREAD

**Issue by LPX-E5BD8** [flike/kingbus#13]
看了代码跟设计架构，作为一个中间件直接介入到数据库集群中，感觉存在这样几个问题：

1. 引入运维复杂度跟风险点，维护数据库集群的时候需要再关注kingbus集群的状态。
2. 同步复杂度增加，同样由于一个raft集群的引入，binlog的传输从之前的点对点变为了点到集群再到点，中间还夹杂着raft一致性保证带来的写放大的问题。即使是内网环境，随着kingbus节点和业务的增长，同步性能与数据安全性的平衡怎么保证？写入量大的场景备份延迟如何保证不能被放大？
3. kingbus集群leader挂掉，等同于所有的从库需要做一次主从切换，并没有减少切换成本。

感觉这个东西做个binlog server来备份、分发数据什么的还可以，至少比canel少了一堆组件要部署，但是作为中间件连接master和slave，感觉稍微有些鸡肋啊。

**Comment by flike** [comment]
定位就是binlog server
